# Types of matrix multiplications

In [4]:
import numpy as np 
import sympy as sp 
from scipy import linalg

In [5]:
matrix_1 = np.array([[1, 2], [3, 4]])

In [6]:
matrix_1 @ matrix_1

array([[ 7, 10],
       [15, 22]])

> ## Hadamard multiplications
$A \circ B =  A \odot B = C$ for $C =[c_{ij}] = [a_{ij}\times b_{ij}]$

In [7]:
matrix_2 = np.arange(0, 25).reshape(5, 5)
matrix_3 = np.arange(1, 26).reshape(5, 5)

In [8]:
matrix_2 # [)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
matrix_3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
matrix_2 * matrix_3

array([[  0,   2,   6,  12,  20],
       [ 30,  42,  56,  72,  90],
       [110, 132, 156, 182, 210],
       [240, 272, 306, 342, 380],
       [420, 462, 506, 552, 600]])

<h1  style="color:red"> BE AWARE OF NUMPY BROADCASTING <h1>

In [11]:
matrix_4 = np.random.rand(3,3)
matrix_5 = np.random.rand(1,3)

In [12]:
matrix_4 * matrix_5 
# this wrong, its the result of numpy broadcasting not hadamard multiplication

array([[0.06431468, 0.76428817, 0.05845882],
       [0.02672887, 0.64253667, 0.20776579],
       [0.10068422, 0.03380799, 0.13062935]])

> # Kronecker matrix  (AKA. Tensor product)
$A \otimes B =  \begin{bmatrix}     a_{11}B & a_{12}B & \dots & a_{1n}B \\     a_{21}B & a_{22}B & \dots & a_{2n}B \\     \vdots & \vdots   & \ddots & \vdots \\     a_{m1}B & a_{m2}B & \dots & a_{mn}B     \end{bmatrix}.$
$\begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix} \otimes \begin{bmatrix} b_{11} & b_{12} & b_{13} \\ b_{21} & b_{22} & b_{23} \end{bmatrix} = \left[\begin{array}{ccc|ccc} a_{11}b_{11} & a_{11}b_{12} & a_{11}b_{13} & a_{12}b_{11} &  a_{12}b_{12} & a_{12}b_{13} \\ a_{11}b_{21} & a_{11}b_{22} & a_{11}b_{23} & a_{12}b_{21} & a_{12}b_{22} & a_{12}b_{23} \\\hline a_{21}b_{11} &  a_{21}b_{12} & a_{21}b_{13} & a_{22}b_{11} &  a_{22}b_{12} & a_{22}b_{13} \\ a_{21}b_{21} & a_{21}b_{22} & a_{21}b_{23} & a_{22}b_{21} & a_{22}b_{22} & a_{22}b_{23} \end{array}\right].$

## $ A_{m,n} \otimes B_{p,q} = C_{m\times p, n \times q} $

In [13]:
matrix_6 = np.arange(4, 13).reshape(3, 3)
matrix_7 = np.array([1, 2, 3])

In [14]:
matrix_6

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
matrix_7

array([1, 2, 3])

In [16]:
np.kron(matrix_6, matrix_7)

array([[ 4,  8, 12,  5, 10, 15,  6, 12, 18],
       [ 7, 14, 21,  8, 16, 24,  9, 18, 27],
       [10, 20, 30, 11, 22, 33, 12, 24, 36]])

In [17]:
np.kron(matrix_7, matrix_6)

array([[ 4,  5,  6,  8, 10, 12, 12, 15, 18],
       [ 7,  8,  9, 14, 16, 18, 21, 24, 27],
       [10, 11, 12, 20, 22, 24, 30, 33, 36]])

> ## $(A\otimes B)^{-1} = A^{-1}\otimes B^{-1}$ 
> ## $ A \otimes (B + C) = (A \otimes B) + (A \otimes C)$
> ## $ A \otimes (B \otimes C) = (A \otimes B) \otimes C$

In [18]:
A_1 = np.random.randint(0, 9, (3, 3))
A_2 = np.random.randint(0, 9, (2, 2))

In [19]:
A_1_inv = np.linalg.inv(A_1)
A_2_inv = np.linalg.inv(A_2)

In [20]:
invk_ = np.kron(A_1_inv, A_2_inv)

In [21]:
kinv_ = np.linalg.inv(np.kron(A_1, A_2))

In [22]:
invk_

array([[ 0.30434783, -0.17391304, -0.04347826,  0.02484472, -0.17391304,
         0.09937888],
       [-0.13043478,  0.2173913 ,  0.01863354, -0.0310559 ,  0.07453416,
        -0.1242236 ],
       [-0.30434783,  0.17391304,  0.04347826, -0.02484472,  0.22463768,
        -0.12836439],
       [ 0.13043478, -0.2173913 , -0.01863354,  0.0310559 , -0.09627329,
         0.16045549],
       [ 0.        , -0.        ,  0.04347826, -0.02484472, -0.02898551,
         0.01656315],
       [-0.        ,  0.        , -0.01863354,  0.0310559 ,  0.01242236,
        -0.02070393]])

In [23]:
kinv_

array([[ 0.30434783, -0.17391304, -0.04347826,  0.02484472, -0.17391304,
         0.09937888],
       [-0.13043478,  0.2173913 ,  0.01863354, -0.0310559 ,  0.07453416,
        -0.1242236 ],
       [-0.30434783,  0.17391304,  0.04347826, -0.02484472,  0.22463768,
        -0.12836439],
       [ 0.13043478, -0.2173913 , -0.01863354,  0.0310559 , -0.09627329,
         0.16045549],
       [ 0.        ,  0.        ,  0.04347826, -0.02484472, -0.02898551,
         0.01656315],
       [ 0.        ,  0.        , -0.01863354,  0.0310559 ,  0.01242236,
        -0.02070393]])

In [24]:
np.all(kinv_== invk_)

False

In [25]:
np.linalg.norm(kinv_ - invk_)

2.109312470471913e-16

> ## Khatri-rao
> ## $\mathrm{A} * \mathrm{B} = [\mathrm{a}_1 \otimes \mathrm{b}_1 \mathrm{a}_2 \otimes \mathrm{b}_2 \ldots \mathrm{a}_k \otimes \mathrm{b}_k]$

In [26]:
matrix_8 = np.array([[1, 2, 3], [4, 5, 6]])
matrix_9 = np.array([[3, 4, 5], [6, 7, 8], [6, 9, 7]])

In [27]:
matrix_8

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
matrix_9

array([[3, 4, 5],
       [6, 7, 8],
       [6, 9, 7]])

In [29]:
linalg.khatri_rao(matrix_8, matrix_9)

array([[ 3,  8, 15],
       [ 6, 14, 24],
       [ 6, 18, 21],
       [12, 20, 30],
       [24, 35, 48],
       [24, 45, 42]])

# Norms

> # Vector norms
> ## $\|A\|_1= \sum_{i=1}^n |a_{ij}|: \text{   Manhatan Norm}$
> ## $\|A\|_2= (\sum_{i=1}^n |a_{ij}|^2)^\frac{1}{2} : \text{  Euclidean Norm}$
> ## $ \left\|\mathbf {x} \right\|_{\infty }:=\max _{i}\left|x_{i}\right| : \infty \text{  Norm}$
> ## $ \left\|\mathbf {x} \right\|_{p}:=\left(\sum _{i=1}^{n}\left|x_{i}\right|^{p}\right)^\frac{1}{p}:  \text{Forbinus Norm}$


> # Norms-induced by p-norm
> ## $\|A\|_{1}=\max _{1\leq j\leq n}\sum _{i=1}^{m}|a_{ij}|$ :  the maximum absolute column sum of the matrix;
> ## $\|A\|_{\infty }=\max _{1\leq i\leq m}\sum _{j=1}^{n}|a_{ij}|$ : simply the maximum absolute row sum of the matrix
> ## $\|A\|_{2}={\sqrt {\lambda _{\max }\left(A^{T}A\right)}}=\sigma _{\max }(A).$

In [30]:
matrix_9 = np.arange(25).reshape(5, 5)

In [31]:
matrix_9

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
np.linalg.norm(matrix_9, ord=None)

70.0

In [33]:
np.linalg.norm(matrix_9, ord=np.inf)

110.0

In [34]:
np.linalg.norm(matrix_9, ord=1)

70.0

In [35]:
np.sum(matrix_9, axis=0 )

array([50, 55, 60, 65, 70])

In [36]:
np.sum(matrix_9, axis=1)

array([ 10,  35,  60,  85, 110])

In [37]:
ATA = matrix_9.T @ matrix_9

In [38]:
np.sqrt(np.max(np.linalg.eig(ATA)[0]))

69.90859404530168

> # Entry wise Norm
> ## $\displaystyle \|A\|_{p,p}=\|\mathrm {vec} (A)\|_{p}=\left(\sum _{i=1}^{m}\sum _{j=1}^{n}|a_{ij}|^{p}\right)^{1/p}$

In [39]:
def norm_entry(matrix , p=2):
    return np.sum(np.abs(matrix)**p)**(1/p)

In [40]:
norm_entry(matrix_9)

70.0

In [41]:
norm_entry(matrix_9, 3)

44.81404746557164

## Distance Matrix

In [42]:
import pandas as pd

In [43]:
data = pd.read_csv(r"C:\Users\Samina\Desktop\coordinate_schools.csv")

In [44]:
data.head(5)

id            N            E
0   1  3949698.628  543976.6419
1   2  3950019.321  543752.2734
2   3  3950019.321  543752.2734
3   4  3950350.812  544520.9178
4   5  3950929.805  544947.7288

In [45]:
def dist_matrix(coordinates):
    d_matrix = np.zeros((coordinates.shape[0], coordinates.shape[0]))
    for i in range(coordinates.shape[0]):
        d_matrix[i, :] = np.sqrt(np.sum((coordinates[i, :] - coordinates[:,:])**2, axis =1))
    return d_matrix

In [46]:
coor = np.array(list(zip(data['E'], data['N'])))

In [47]:
pd.DataFrame(dist_matrix(coor))

0             1             2             3            4   \
0       0.000000    391.388840    391.388840    849.458784  1568.058217   
1     391.388840      0.000000      0.000000    837.078549  1502.695820   
2     391.388840      0.000000      0.000000    837.078549  1502.695820   
3     849.458784    837.078549    837.078549      0.000000   719.305584   
4    1568.058217   1502.695820   1502.695820    719.305584     0.000000   
5    1409.501840   1255.323224   1255.323224    633.656267   395.240977   
6    1417.786515   1262.405942   1262.405942    642.600204   396.239071   
7    1707.640925   1508.319102   1508.319102    966.547104   576.844330   
8    2985.765943   2839.670139   2839.670139   2155.252086  1455.125892   
9    4411.126016   4272.849867   4272.849867   3571.665887  2857.857941   
10   4662.599901   4491.424958   4491.424958   3839.439868  3140.494599   
11   4655.137341   4479.862105   4479.862105   3834.718158  3138.508800   
12   4735.845799   4533.965787   4533.965787   3936.319890  3261.151073   
13   5212.245307   4989.217780   4989.217780   4431.889053  3774.049924   
14   5211.058235   4989.816169   4989.816169   4428.747795  3768.934531   
15   5217.612516   4998.108013   4998.108013   4433.397863  3771.626660   
16   5267.029830   5056.990416   5056.990416   4472.952906  3801.059922   
17   5632.706854   5442.358936   5442.358936   4820.326781  4129.573383   
18   5658.730389   5470.510313   5470.510313   4844.663582  4152.273902   
19   5815.282539   5601.428460   5601.428460   5022.988244  4350.956783   
20   6168.025831   5985.428880   5985.428880   5348.811047  4650.903725   
21   6171.712447   5988.754645   5988.754645   5352.739026  4655.042167   
22   6241.674245   6058.333788   6058.333788   5422.834371  4725.166478   
23   6252.507861   6068.788734   6068.788734   5433.910182  4736.443893   
24   6606.511503   6429.789033   6429.789033   5782.715570  5080.338626   
25   6610.118833   6427.872202   6427.872202   5789.902512  5090.602657   
26   9989.781209  10027.047113  10027.047113   9193.542934  8545.576133   
27  11157.345415  11211.836867  11211.836867  10375.728932  9742.782423   
28  11250.265670  11302.286057  11302.286057  10466.468561  9831.025174   
29  11302.809117  11328.385537  11328.385537  10497.877905  9838.782414   

              5             6             7            8            9   ...  \
0    1409.501840   1417.786515   1707.640925  2985.765943  4411.126016  ...   
1    1255.323224   1262.405942   1508.319102  2839.670139  4272.849867  ...   
2    1255.323224   1262.405942   1508.319102  2839.670139  4272.849867  ...   
3     633.656267    642.600204    966.547104  2155.252086  3571.665887  ...   
4     395.240977    396.239071    576.844330  1455.125892  2857.857941  ...   
5       0.000000      8.945693    335.772308  1587.627489  3020.044803  ...   
6       8.945693      0.000000    326.919297  1580.067569  3012.585464  ...   
7     335.772308    326.919297      0.000000  1349.479948  2777.921208  ...   
8    1587.627489   1580.067569   1349.479948     0.000000  1433.182368  ...   
9    3020.044803   3012.585464   2777.921208  1433.182368     0.000000  ...   
10   3255.220116   3247.181900   2983.272370  1685.828296   470.919090  ...   
11   3246.825243   3238.723328   2971.543101  1683.384686   511.936386  ...   
12   3328.041075   3319.577822   3032.764053  1820.652343   861.478048  ...   
13   3812.556143   3803.888943   3504.606524  2353.133843  1378.776219  ...   
14   3810.346420   3801.695845   3503.438844  2345.182374  1357.060507  ...   
15   3815.949965   3807.316279   3510.084155  2345.071802  1341.219767  ...   
16   3861.168636   3852.634187   3561.218747  2361.432669  1270.844596  ...   
17   4223.208454   4214.920553   3936.731283  2675.065095  1395.812772  ...   
18   4249.246215   4240.986664   3964.265564  2697.379880  1404.791572  ...   
19   4410.322076   4401.765679   4108.707173  2909.105019  1740.989156  ...   
20   4759.005412   4750.83053