In [4]:
import numpy as np
import sympy as sp

<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Eigenvalue_equation.svg/750px-Eigenvalue_equation.svg.png'>

In [5]:
B = np.arange(25).reshape(5,5)

In [7]:
eigval, eigvec = np.linalg.eig(B)

In [11]:
eigval

array([ 6.39116499e+01+0.00000000e+00j, -3.91164992e+00+0.00000000e+00j,
       -3.22069971e-15+0.00000000e+00j,  2.58587115e-16+7.36422729e-16j,
        2.58587115e-16-7.36422729e-16j])

In [12]:
sp.Matrix(eigvec)

Matrix([
[-0.0851802044442117,  0.677798642251155,  0.241097553402141,  0.231527951929876 - 0.124691772032449*I,  0.231527951929876 + 0.124691772032449*I],
[  -0.23825371650214,  0.363488728108324, -0.540613258597661, -0.210541310742987 - 0.102154705576812*I, -0.210541310742987 + 0.102154705576812*I],
[ -0.391327228560067, 0.0491788139654932, -0.025510055388677,  0.184263276168906 + 0.402615602430115*I,  0.184263276168906 - 0.402615602430115*I],
[ -0.544400740617995, -0.265131100177339,  0.708469672961775,                        -0.66301442782836,                        -0.66301442782836],
[ -0.697474252675922, -0.579441014320168, -0.383443912377578,  0.457764510472563 - 0.175769124820855*I,  0.457764510472563 + 0.175769124820855*I]])

## multiplication of eigenvalues equals the determinant

In [13]:
np.prod(eigval)

(4.905010774696372e-43+1.9913648889155653e-59j)

In [15]:
np.linalg.det(B)

0.0

In [17]:
eigval2, eigvec2 = np.linalg.eig(B * 2)

In [18]:
eigval2

array([ 1.27823300e+02+0.00000000e+00j, -7.82329983e+00+0.00000000e+00j,
       -6.44139942e-15+0.00000000e+00j,  5.17174229e-16+1.47284546e-15j,
        5.17174229e-16-1.47284546e-15j])

In [20]:
eigval * 2

array([ 1.27823300e+02+0.00000000e+00j, -7.82329983e+00+0.00000000e+00j,
       -6.44139942e-15+0.00000000e+00j,  5.17174229e-16+1.47284546e-15j,
        5.17174229e-16-1.47284546e-15j])

## $A = USV^T$

In [21]:
A = B.copy()

In [39]:
sigma1, v = np.linalg.eig(A.T@A)

In [40]:
sp.Matrix(v)

Matrix([
[ -0.39024378383877,  -0.669111193431407,   -0.632455532033667, -0.547170528442977,   0.332527805825227],
[-0.417873543306904,  -0.354092786998172,    0.632455532033681,  0.402151674967912, -0.0534318404368215],
[-0.445503302775037, -0.0390743805649295,    0.316227766016827,  0.640825626693196,  -0.260328728570996],
[ -0.47313306224317,   0.275944025868273, 1.61910600334024e-14, -0.299424164518183,  -0.649158244848487],
[-0.500762821711303,   0.590962432301532,   -0.316227766016856, -0.196382608699947,   0.630391008031075]])

In [41]:
sigma2, v1 = np.linalg.eig(A@A.T)

In [42]:
sp.Matrix(v1)

Matrix([
[-0.0676788124127592, -0.771634355346103,    -0.632455532033674, -0.529609021408192, -0.586470199500882],
[ -0.226995170029086, -0.498470854497501,     0.632455532033679,  0.324514475448184,  0.396377910641437],
[ -0.386311527645414, -0.225307353648892,     0.316227766016838,   0.37569436370224,  0.489418015474921],
[ -0.545627885261741, 0.0478561471997163, -2.59421450309763e-15,  0.393503931883723,  0.177911035129372],
[ -0.704944242878068,   0.32101964804832,    -0.316227766016837, -0.564103749625958, -0.477236761744849]])

In [43]:
u, s, vt = np.linalg.svd(A)

In [44]:
sp.Matrix(u) # eigenvectors of AAT

Matrix([
[-0.067678812412759, -0.771634355346103,  0.484260998257148, -0.403633984232488, 0.0507039676909056],
[-0.226995170029086, -0.498470854497499, -0.399729761643295,  0.569748511875296,  0.464330432851951],
[-0.386311527645413, -0.225307353648892, -0.099917329738488,  0.269213542697828,   -0.8470776798181],
[-0.545627885261741, 0.0478561471997144, -0.538020048621724, -0.633136684091597, 0.0983481903167243],
[-0.704944242878068,  0.321019648048321,  0.553406141746361,   0.19780861375096,  0.233695088958519]])

In [45]:
sp.Matrix(vt) # eigenvectors of ATA

Matrix([
[  -0.39024378383877, -0.417873543306903, -0.445503302775037,   -0.47313306224317, -0.500762821711303],
[  0.669111193431405,  0.354092786998173, 0.0390743805649402,  -0.275944025868291, -0.590962432301524],
[ 0.0421562707582297, -0.292255537998404,  0.674570360444015,  -0.640999189925734,  0.216528096721894],
[ -0.630999186596368,  0.620412393515566,  0.356156058607006, -0.0495525513752345, -0.296016714150968],
[0.00792939786366179,   0.47924436614482, -0.467020011057293,   -0.53541066777452,  0.515256914823331]])

## $\Lambda$

In [50]:
np.sqrt(sigma1.astype(np.complex128))

array([6.99085940e+01+0.00000000e+00j, 3.57609824e+00+0.00000000e+00j,
       2.71457824e-07+0.00000000e+00j, 3.06724707e-07+0.00000000e+00j,
       0.00000000e+00+1.70674452e-07j])

In [51]:
np.sqrt(sigma2.astype(np.complex128))

array([6.99085940e+01+0.00000000e+00j, 3.57609824e+00+0.00000000e+00j,
       0.00000000e+00+2.06378473e-07j, 1.87352718e-07+0.00000000e+00j,
       2.95459002e-08+0.00000000e+00j])

In [33]:
s

array([6.99085940e+01, 3.57609824e+00, 2.75054272e-15, 1.17184055e-15,
       5.64586018e-17])

In [52]:
np.linalg.cond(A)

1.2382275114099835e+18

## Column space: Since A is rank k, the first k left singular vectors,(the columns of U), provide an orthonormal basis for the column space of A.

## Row space: Similarly, the first k right singular vectors (the columns of V , or the rows of V Transpose), provide an orthonormal basis for the row space of A.

## Null space: The last right singular vectors(the last columns of V , or the last rows of V Transpose), provide an orthonormal basis for the null space of A.

In [56]:
np.linalg.matrix_rank(A)

2

In [53]:
sp.Matrix(u)

Matrix([
[-0.067678812412759, -0.771634355346103,  0.484260998257148, -0.403633984232488, 0.0507039676909056],
[-0.226995170029086, -0.498470854497499, -0.399729761643295,  0.569748511875296,  0.464330432851951],
[-0.386311527645413, -0.225307353648892, -0.099917329738488,  0.269213542697828,   -0.8470776798181],
[-0.545627885261741, 0.0478561471997144, -0.538020048621724, -0.633136684091597, 0.0983481903167243],
[-0.704944242878068,  0.321019648048321,  0.553406141746361,   0.19780861375096,  0.233695088958519]])

In [57]:
sp.Matrix(v)

Matrix([
[ -0.39024378383877,  -0.669111193431407,   -0.632455532033667, -0.547170528442977,   0.332527805825227],
[-0.417873543306904,  -0.354092786998172,    0.632455532033681,  0.402151674967912, -0.0534318404368215],
[-0.445503302775037, -0.0390743805649295,    0.316227766016827,  0.640825626693196,  -0.260328728570996],
[ -0.47313306224317,   0.275944025868273, 1.61910600334024e-14, -0.299424164518183,  -0.649158244848487],
[-0.500762821711303,   0.590962432301532,   -0.316227766016856, -0.196382608699947,   0.630391008031075]])

## Pseudo inverse

In [60]:
# np.linalg.inv(B) #  Singular matrix

## $\displaystyle \left[\begin{matrix}0 & 1 & 2 & 3 & 4\\5 & 6 & 7 & 8 & 9\\10 & 11 & 12 & 13 & 14\\15 & 16 & 17 & 18 & 19\\20 & 21 & 22 & 23 & 24\end{matrix}\right]\left[\begin{matrix}x_1\\ x_2\\x_3\\x_4\\x_5\end{matrix}\right] = \left[\begin{matrix}1\\ 2\\3\\4\\5\end{matrix}\right]$

In [68]:
pinvb = np.linalg.pinv(B)

In [69]:
sp.Matrix(pinvb)

Matrix([
[              -0.144,  -0.0920000000000002,  -0.0400000000000001,                 0.012,  0.0640000000000001],
[              -0.076,  -0.0480000000000001,  -0.0200000000000001,   0.00800000000000002,  0.0360000000000001],
[-0.00799999999999991, -0.00399999999999995, 1.90274969969361e-17,                 0.004, 0.00799999999999997],
[  0.0599999999999999,                 0.04,                 0.02, -1.06763587214137e-17,               -0.02],
[               0.128,   0.0840000000000003,   0.0400000000000001,  -0.00400000000000004, -0.0480000000000001]])

In [66]:
l = np.arange(1,6).reshape(5, 1)

In [70]:
pinvb @ l

array([[-0.08],
       [-0.02],
       [ 0.04],
       [ 0.1 ],
       [ 0.16]])