![knlogo](https://wp.kntu.ac.ir/aliakbarian/ode/images/logo.png)

<h1 style="color:Gray"> A Crash course on Python programming scientific-algebric inclined</h1>
<h2 style="color:Gray font'Serif'"> Linear Algebra </h2>
<h2 style="color:Gray"> Dr. Mohammadreza Malek </h2>
<h3 style="color:Gray"> Amirhesam Taherzadegani </h3>
<h4 style="color:Gray"> Geomatics engineering and geodesy faculty , KNTU </h4>

In [1]:
import numpy as np # numerical python
import sympy as sp # symbolic python

## Transpose

## $ A^{T}_{i,j} = A_{j,i} $

In [2]:
m1 = np.array([[1, 2, 3],
              [3, 4, 5],
              [6, 7, 8]])

In [3]:
m1transpose = m1.T
m1transpose

array([[1, 3, 6],
       [2, 4, 7],
       [3, 5, 8]])

## $(A + B)^T = A^T + B^T$

In [4]:
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

In [5]:
assert np.all(A.T + B.T == (A + B).T) # the properties upholds

## Trace

## $ Trace(A) = \sum^n_{i=0} a_{ii}$

In [6]:
A

array([[6, 9, 7],
       [7, 1, 9],
       [2, 1, 5]])

In [7]:
result = 0
for i in range(A.shape[0]):
    result += A[i, i]
result

12

In [8]:
np.trace(A)

12

## Decomposition of a matrix to sum of a symmetric and a skew-symmetric matrix

## $M = \frac{A + A^T}{2},N = \frac{A - A^T}{2} \to A = M + N$

## $\text{for a matrix to be symmetric, following should uphold: } A^T = A$
## $\text{for a matrix to be skew symmetric, following should uphold: } A^T = -A$

In [9]:
def decompose(A):
    m, n = 0.5 * (A + A.T), 0.5 * (A - A.T)
    return m, n

In [10]:
m, n = decompose(A)
print("m: sym")
display(sp.Matrix(m))
print("*"*20)
print("n: skew-sym")
display(sp.Matrix(n))
print("*"*20)
display(sp.Matrix(A))

m: sym


Matrix([
[6.0, 8.0, 4.5],
[8.0, 1.0, 5.0],
[4.5, 5.0, 5.0]])

********************
n: skew-sym


Matrix([
[ 0.0,  1.0, 2.5],
[-1.0,  0.0, 4.0],
[-2.5, -4.0, 0.0]])

********************


Matrix([
[6, 9, 7],
[7, 1, 9],
[2, 1, 5]])

## Idempotent matrix

## $A^K = A$

In [11]:
idem_a = np.array([[2, -2, -4],
                  [-1, 3, 4],
                  [1, -2, -3]])

In [12]:
for _ in range(10000):
    idem_a = idem_a  @ idem_a 

In [13]:
idem_a

array([[ 2, -2, -4],
       [-1,  3,  4],
       [ 1, -2, -3]])

## Nilpotent

## $A^K = 0 \to \text{we say its a k degree nilpotent}$

In [14]:
nil_potent = np.zeros((3, 3))
nil_potent[0, 1] = 1
nil_potent[1, -1] = 1

In [15]:
nil_potent

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [16]:
degree = 0
while np.any(nil_potent != 0):
    degree += 1
    nil_potent = nil_potent @ nil_potent

In [17]:
degree

2

## Normal Inverses

In [18]:
mat_1  = np.random.randint(1, 26, (5, 5)) #[)
mat_1

array([[ 3,  6, 15,  5, 16],
       [ 7, 25, 15,  7, 25],
       [15, 25, 11, 17, 11],
       [24,  8, 12, 11,  2],
       [11,  3, 11,  2, 22]])

In [19]:
mat_1sp = sp.Matrix(mat_1)
mat_1sp

Matrix([
[ 3,  6, 15,  5, 16],
[ 7, 25, 15,  7, 25],
[15, 25, 11, 17, 11],
[24,  8, 12, 11,  2],
[11,  3, 11,  2, 22]])

In [20]:
mat_2 = sp.Matrix(np.linalg.inv(mat_1))
mat_2

Matrix([
[-0.0591302293997815,  0.0192627911782941, -0.0227672640311771,  0.0446340527294736,  0.0284402586283251],
[-0.0389654866995365,  0.0766791650674618,  -0.028708925039119,  0.0217235983584778, -0.0464172891263913],
[ 0.0909391514865224,  0.0420994360957751, -0.0732086445631956,   0.060074990404771, -0.0828348734905966],
[ 0.0610787989725724,  -0.138531487112869,   0.143349768238316, -0.0790587818487792,  0.0485134776062118],
[-0.0161436036727584, -0.0285435918632458,  0.0388710105990375, -0.0481296684479348,   0.074571167075079]])

In [21]:
mat_1sp.inv()

Matrix([
[-10014/169355,  13049/677420, -15423/677420,   7559/169355,   9633/338710],
[ -6599/169355,  12986/169355,  -4862/169355,   3679/169355,  -7861/169355],
[ 15401/169355,  28519/677420, -49593/677420,  10174/169355, -28057/338710],
[ 10344/169355, -23461/169355,  24277/169355, -13389/169355,   8216/169355],
[ -2734/169355,  -4834/169355,   6583/169355,  -8151/169355,  12629/169355]])

In [22]:
mat_1sp.charpoly()

PurePoly(lambda**5 - 72*lambda**4 + 514*lambda**3 + 7502*lambda**2 - 40745*lambda - 677420, lambda, domain='ZZ')

In [23]:
sp.Matrix([[1, 2],[3,4]]).charpoly().as_expr()

lambda**2 - 5*lambda - 2

<a href="https://www.emathhelp.net/calculators/linear-algebra/reduced-row-echelon-form-rref-caclulator/" style=" background-color: black;
  color: grey;
  border: 2px dashed grey;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;">Step by step RREF(emathhelp)</a>

In [24]:
gj = np.hstack([mat_1, np.eye(5)])

In [25]:
gj_sp = sp.Matrix(gj)
gj_sp

Matrix([
[ 3.0,  6.0, 15.0,  5.0, 16.0, 1.0, 0.0, 0.0, 0.0, 0.0],
[ 7.0, 25.0, 15.0,  7.0, 25.0, 0.0, 1.0, 0.0, 0.0, 0.0],
[15.0, 25.0, 11.0, 17.0, 11.0, 0.0, 0.0, 1.0, 0.0, 0.0],
[24.0,  8.0, 12.0, 11.0,  2.0, 0.0, 0.0, 0.0, 1.0, 0.0],
[11.0,  3.0, 11.0,  2.0, 22.0, 0.0, 0.0, 0.0, 0.0, 1.0]])

In [26]:
gj_sp.rref()[0]

Matrix([
[1, 0, 0, 0, 0, -0.0591302293997815,  0.0192627911782941, -0.0227672640311771,  0.0446340527294736,  0.0284402586283251],
[0, 1, 0, 0, 0, -0.0389654866995365,  0.0766791650674618,  -0.028708925039119,  0.0217235983584778, -0.0464172891263913],
[0, 0, 1, 0, 0,  0.0909391514865224,  0.0420994360957751, -0.0732086445631957,   0.060074990404771, -0.0828348734905967],
[0, 0, 0, 1, 0,  0.0610787989725724,  -0.138531487112869,   0.143349768238316, -0.0790587818487792,  0.0485134776062118],
[0, 0, 0, 0, 1, -0.0161436036727584, -0.0285435918632458,  0.0388710105990375, -0.0481296684479348,   0.074571167075079]])

In [27]:
arr_1 = sp.matrix2numpy(gj_sp.rref()[0]).astype(np.float64)

In [28]:
inv_arr = arr_1[:, 5:]

In [30]:
sp.Matrix(inv_arr)

Matrix([
[-0.0591302293997815,  0.0192627911782941, -0.0227672640311771,  0.0446340527294736,  0.0284402586283251],
[-0.0389654866995365,  0.0766791650674618,  -0.028708925039119,  0.0217235983584778, -0.0464172891263913],
[ 0.0909391514865224,  0.0420994360957751, -0.0732086445631957,   0.060074990404771, -0.0828348734905967],
[ 0.0610787989725724,  -0.138531487112869,   0.143349768238316, -0.0790587818487792,  0.0485134776062118],
[-0.0161436036727584, -0.0285435918632458,  0.0388710105990375, -0.0481296684479348,   0.074571167075079]])