In [2]:
import numpy as np 
import sympy as sp
from scipy import linalg

## LU decomposition

## ${\displaystyle {\begin{bmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{bmatrix}}={\begin{bmatrix}\ell _{11}&0&0\\\ell _{21}&\ell _{22}&0\\\ell _{31}&\ell _{32}&\ell _{33}\end{bmatrix}}{\begin{bmatrix}u_{11}&u_{12}&u_{13}\\0&u_{22}&u_{23}\\0&0&u_{33}\end{bmatrix}}.}$

# without permutation
# $A = LU$

# with permutation
# $A = PLU$

In [5]:
A = np.arange(25).reshape(5,5)

In [6]:
sp.Matrix(A)

Matrix([
[ 0,  1,  2,  3,  4],
[ 5,  6,  7,  8,  9],
[10, 11, 12, 13, 14],
[15, 16, 17, 18, 19],
[20, 21, 22, 23, 24]])

In [8]:
p, l, u = linalg.lu(A)

In [12]:
display(sp.Matrix(p))
display(sp.Matrix(l))
display(sp.Matrix(u))

Matrix([
[  0, 1.0,   0,   0,   0],
[  0,   0,   0,   0, 1.0],
[  0,   0, 1.0,   0,   0],
[  0,   0,   0, 1.0,   0],
[1.0,   0,   0,   0,   0]])

Matrix([
[ 1.0,    0,   0,   0,   0],
[   0,  1.0,   0,   0,   0],
[ 0.5,  0.5, 1.0,   0,   0],
[0.75, 0.25,   0, 1.0,   0],
[0.25, 0.75,   0,   0, 1.0]])

Matrix([
[20.0, 21.0, 22.0, 23.0, 24.0],
[   0,  1.0,  2.0,  3.0,  4.0],
[   0,    0,    0,    0,    0],
[   0,    0,    0,    0,    0],
[   0,    0,    0,    0,    0]])

In [14]:
p @ l @ u

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

https://math.stackexchange.com/questions/1880573/lu-decomposition-vs-cholesky-decomposition

## Cholesky (if and only if your matrix is positive definitive)

# $A = LL^T$

In [16]:
# l = np.linalg.cholesky(A) # Matrix is not positive definite

In [25]:
mat1 = np.array([[8, 3],
                [3, 6]])

In [26]:
l = np.linalg.cholesky(mat1)

In [29]:
display(sp.Matrix(mat1))
display(sp.Matrix(l))

Matrix([
[8, 3],
[3, 6]])

Matrix([
[2.82842712474619,                0],
[1.06066017177982, 2.20794021658196]])

In [27]:
l @ l.T

array([[8., 3.],
       [3., 6.]])

## QR

## ${\displaystyle {\begin{aligned}\mathbf {u} _{1}&=\mathbf {a} _{1},&\mathbf {e} _{1}&={\frac {\mathbf {u} _{1}}{\|\mathbf {u} _{1}\|}}\\\mathbf {u} _{2}&=\mathbf {a} _{2}-\operatorname {proj} _{\mathbf {u} _{1}}\mathbf {a} _{2},&\mathbf {e} _{2}&={\frac {\mathbf {u} _{2}}{\|\mathbf {u} _{2}\|}}\\\mathbf {u} _{3}&=\mathbf {a} _{3}-\operatorname {proj} _{\mathbf {u} _{1}}\mathbf {a} _{3}-\operatorname {proj} _{\mathbf {u} _{2}}\mathbf {a} _{3},&\mathbf {e} _{3}&={\frac {\mathbf {u} _{3}}{\|\mathbf {u} _{3}\|}}\\&\;\;\vdots &&\;\;\vdots \\\mathbf {u} _{k}&=\mathbf {a} _{k}-\sum _{j=1}^{k-1}\operatorname {proj} _{\mathbf {u} _{j}}\mathbf {a} _{k},&\mathbf {e} _{k}&={\frac {\mathbf {u} _{k}}{\|\mathbf {u} _{k}\|}}\end{aligned}}}$

# ${\displaystyle Q={\begin{bmatrix}\mathbf {e} _{1}&\cdots &\mathbf {e} _{n}\end{bmatrix}}}$

## ${\displaystyle R={\begin{bmatrix}\langle \mathbf {e} _{1},\mathbf {a} _{1}\rangle &\langle \mathbf {e} _{1},\mathbf {a} _{2}\rangle &\langle \mathbf {e} _{1},\mathbf {a} _{3}\rangle &\cdots \\0&\langle \mathbf {e} _{2},\mathbf {a} _{2}\rangle &\langle \mathbf {e} _{2},\mathbf {a} _{3}\rangle &\cdots \\0&0&\langle \mathbf {e} _{3},\mathbf {a} _{3}\rangle &\cdots \\\vdots &\vdots &\vdots &\ddots \end{bmatrix}}.}$

In [30]:
q, r = np.linalg.qr(A)

In [32]:
sp.Matrix(q)

Matrix([
[                 0,   -0.774596669241482,   0.62041604233261, -0.0963687521223961, 0.0761380196138304],
[-0.182574185835055,   -0.516397779494324, -0.654433550925211,    0.28324872277586,   0.43759214854618],
[-0.365148371670111,   -0.258198889747162, -0.189737503803796,   0.177686165594704, -0.855819669209907],
[-0.547722557505166, 5.55111512312578e-16, -0.138888508947204,  -0.819643491027409, 0.0943108143259549],
[-0.730296743340221,    0.258198889747162,  0.362643521343603,   0.455077354779239,  0.247778686723943]])

In [38]:
np.linalg.norm(q[:, 3]) # magnitude equals one

0.9999999999999999

In [40]:
q[0].dot(q[1]) # orthogonality of rows

-2.1510571102112408e-16

In [41]:
q[:, 0].dot(q[:, 1]) # orthogonality of rows

-1.1102230246251565e-16

In [42]:
q @ r

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [46]:
sp.Matrix(np.round(q.T @ q, 10))

Matrix([
[1.0,   0,   0,   0,   0],
[  0, 1.0,   0,   0,   0],
[  0,   0, 1.0,   0,   0],
[  0,   0,   0, 1.0,   0],
[  0,   0,   0,   0, 1.0]])